name: Build Android

on:
  push:
    branches:
      - tof_recorder
      - reversion-4
  pull_request:
    branches:
      - tof_recorder
      - reversion-4

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "20"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn export

      - name: Build with Gradle
        working-directory: android
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
