name: Publish Play Store

on:
  release:
    types: [published]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Sync capacitor
        run: npx cap sync

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r21d

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android keystore
        working-directory: ./android
        run: |
          echo $ANDROID_KEYSTORE | base64 -di > sensebox-bike.keystore
          ls -lah
        env:
          ANDROID_KEYSTORE: ${{ secrets.GOOGLE_PLAY_ANDROID_KEYSTORE }}

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: ./android/app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: '[.aab] Build with Gradle'
        working-directory: ./android
        run: ./gradlew app:bundleRelease
        env:
          ANDROID_PATH_TO_KEYSTORE: '../sensebox-bike.keystore'
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_PASSWORD }}

      - name: '[.aab] Archive build artifact'
        uses: actions/upload-artifact@master
        with:
          name: aab-artifact
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: '[.apk] Build with Gradle'
        working-directory: ./android
        run: ./gradlew app:assembleRelease
        env:
          ANDROID_PATH_TO_KEYSTORE: '../sensebox-bike.keystore'
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.GOOGLE_PLAY_ANDROID_KEY_PASSWORD }}

      - name: '[.apk] Archive build artifact'
        uses: actions/upload-artifact@master
        with:
          name: apk-artifact
          path: android/app/build/outputs/apk/release/app-release.apk

  deploy-android:
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: aab-artifact
          path: ./

      - name: Upload on play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: de.reedu.sensebox-bike
          releaseFiles: app-release.aab
